---
abstract: 'Parser for XML logfiles of the Resusci Anne Skills Station software'
author:
  - 'Lieven Hollevoet <hollie@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-ResusciAnneparser
requires:
  Carp: 0
  Data::Dumper: 0
  DateTime: 0
  Moose: 0
  XML::Simple: 0
  autodie: 0
  namespace::autoclean: 0
  perl: 5.012
  strict: 0
resources:
  bugtracker: https://github.com/hollie/text-resuscianneparser-perl/issues
  repository: git://github.com/hollie/text-resuscianneparser-perl.git
version: 0.02
